name: Download via URL

on:
  push:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Download File
        run: |
          FILE_URL="http://ebonini.com.br/teste.txt"
          FILE_NAME="teste.txt"
          curl -LJO $FILE_URL
          mv $FILE_NAME ./epgauto/$FILE_NAME
