name: Download File with curl

on:
  push:
    branches:
      - main
jobs:
  wget:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Download using wget
        run: wget -O sample.html https://httpbin.org/html
