name: Download File with curl

on:
  push:
    branches:
      - main

jobs:
  download-file:
    runs-on: ubuntu-latest

    steps:
      - name: Download file
        run: curl -L -o teste.xml.gz https://ebonini.com.br/teste.txt
