name: Sync EPG 4

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'    # At 01:00 every day UTC
    - cron: '0 13 * * *'  # At 13:00 every day UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download file
      run: |
        wget -O epg4.xml.gz http://m3u4u.com/epg/4z2xnjr445t2wdwvnv15

    - name: Commit and push if it changed
      run: |
        git config user.name "Automated"
        git config user.email "eduardo@ebonini.com.br"
        git add -A
        timestamp=$(date -u)
        git commit -m "Automated download at $timestamp" || exit 0
        git push
