name: Sync EPG 4

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'    # A cada 3 horas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download file
      run: |
        wget -O epg4.xml.gz http://m3u4u.com/epg/w16vy5vpp1cx6972n39p

    - name: Commit and push if it changed
      run: |
        git config user.name "Automated"
        git config user.email "eduardo@ebonini.com.br"
        git add -A
        timestamp=$(date -u)
        git commit -m "Automated download at $timestamp" || exit 0
        git push
