name: Download File with curl

on:
  push:
    branches:
      - main

jobs:
  download-file:
    runs-on: ubuntu-latest

    steps:
      - name: Download file
        run: wget -O teste.txt https://ebonini.com.br/teste.txt
